#!/bin/bash

echo "=========================================="
echo "  Test de Conectividad en Red Pública"
echo "=========================================="
echo ""

# Obtener IP actual
MY_IP=$(hostname -I | awk '{print $1}')

echo "Tu IP actual es: $MY_IP"
echo ""
echo "=========================================="
echo "PRUEBA ESTO EN OTRO DISPOSITIVO:"
echo "=========================================="
echo ""
echo "1. Desde Windows:"
echo "   ping $MY_IP"
echo ""
echo "2. Desde Linux/Mac:"
echo "   ping $MY_IP"
echo ""
echo "3. Test de puerto 4444:"
echo "   telnet $MY_IP 4444"
echo "   (o usa: nc -zv $MY_IP 4444)"
echo ""
echo "=========================================="
echo "INTERPRETACIÓN:"
echo "=========================================="
echo ""
echo "✅ Si el ping FUNCIONA:"
echo "   - La red permite conexiones directas"
echo "   - Usa tu IP ($MY_IP) en los agentes"
echo ""
echo "❌ Si el ping NO FUNCIONA:"
echo "   - Hay aislamiento de clientes (común en redes públicas)"
echo "   - SOLUCIÓN: Usa ngrok para crear un túnel"
echo "   - Comando: ngrok tcp 4444"
echo ""
echo "=========================================="
echo ""
read -p "Presiona ENTER para verificar puertos abiertos localmente..."

echo ""
echo "Verificando si el puerto 4444 está escuchando:"
sudo ss -tlnp | grep 4444 || echo "❌ Puerto 4444 NO está escuchando (inicia el servidor primero)"

echo ""
echo "Estado del firewall:"
sudo firewall-cmd --list-ports 2>/dev/null || echo "Firewall no está usando firewalld"
